### PR TITLE
Boolean values

### PR DESCRIPTION
**Pull request by enr**
Hi,
thank you for this library.

I noticed a problem handling fields when a literal value starting with `n`, `f` or `t` is supplied.

The error is shown [in this test](https://github.com/enr/jsonwheel/blob/invalid-literal/src/test/java/com/romanboehm/jsonwheel/WheelNodeTest.java#L95) which is passing when ran against the current code.

This PR offers a fix and some test for it.

Cheers, Enrico

### CODE REVIEW

**Comment by romanboehm** [comment]
Hey Enrico,

I‘m very glad JSONWheel is of use to you! And thanks for the PR.

May I ask what’s the use case (or problem?) behind the PR? As far as I can tell by looking at [the JSON spec](https://www.json.org/json-en.html), the only values _not_ starting with either `{`, `[`, `“`, `-`, or a digit are the three literals `true`, `false`, and `null`.
Since all three of them start with different letters, there should be no ambiguity once we’re past the initial letter.

If this is about guarding against malformed JSON: I‘m aware JSONWheel is unsafe in that regard. It’s also opinionated in the same regard as it does not aim to handle all malformed inputs — only in a few cases. This helps keep the codebase small.
Maybe I will strive in future to either not validate anything at all, or validate more (like with your suggestion). Currently, there are no such plans, however.

Roman

**Comment by enr** [comment]
Hi @romanboehm ,
I fully understand the desire to keep the codebase small even at the expense of full validation, the problem (_IMHO_) is inconsistent behavior between two equally invalid values.

While this code 

```java
String json = """
        {
            "foo": error,
            "bar": "baz"
        }""";

WheelNode root = JsonWheel.read(json);
```

causes an error, this (only because the invalid value starts with `t`) 

```java
String json = """
        {
            "foo": thisistrue,
            "bar": "baz"
        }""";

WheelNode root = JsonWheel.read(json);
System.err.println("foo: " + root.get("foo").val(Boolean.class));
System.err.println("bar: " + root.get("bar").val(String.class));
```

is considered valid and has as output:

```
foo: true
bar: null
```

It is a very unlikely error but it can happen on json edited by hand.

Enrico

**Comment by romanboehm** [comment]
Hey Enrico,

Thanks for the explanation. Made total sense to me. :) I squash-merged the PR, modified the validation logic a bit to my taste, but kept your original author info. Hope that's fine with you.

Your changes landed in v1.1

Cheers,
Roman

**Comment by enr** [comment]
Great!
Thank you Roman
Enrico

**Pull request merged**
